---
!!com.openkoda.service.export.dto.EventListenerEntryConversionDto
consumerClassName: "com.openkoda.core.customisation.ServerJSRunner"
consumerMethodName: "startCustomisationServerJs"
consumerParameterClassName: "java.time.LocalDateTime"
eventClassName: "com.openkoda.core.service.event.ApplicationEvent"
eventName: "APPLICATION_STARTED"
eventObjectType: "java.time.LocalDateTime"
indexString: "com.openkoda.core.service.event.applicationevent application_started java.time.localdatetime com.openkoda.core.customisation.serverjsrunner startcustomisationserverjs"
staticData1: "forms"
staticData2: "0"
staticData3: "0"
staticData4: "0"